### ISSUE TITLE
Music does not play/is not audible

### ISSUE THREAD

**Issue by jr0n** [PanchamBro/minecraft-music-disc-madness#1]
I've added Music Disc Madness to my server's datapacks directory and manually dropped the Music Disc Madness Resource Pack.zip into Prism Launcher. I can generate the new discs using the provided /give commands but no audio plays when the discs are added to the jukebox. The server was restarted when Music Disc Madness.zip was added.

minecraft@mc:~/survival.6.29.24/datapacks$ ls -la
-rw-rw-r--  1 minecraft minecraft 303035 Jun 19 01:21 'Music Disc Madness.zip'

![image](https://github.com/user-attachments/assets/7bd920c3-3ad9-46c8-b859-2c29a8d45410)

The resource packs also don't show up when searching for it in prism: 

![image](https://github.com/user-attachments/assets/d36a29a8-37f5-4c2c-b14d-99fa8a4fbbe7)

It is very possible I'm installing the packages incorrectly, if so, additional information on installation would be greatly appreciated. Thank you!

**Comment by PanchamBro** [comment]
Hello.

I would like to know where you downloaded the datapack so I can check on the files real quickly.

**Comment by jr0n** [comment]
> I would like to know where you downloaded the datapack so I can check on the files real quickly.

The files were downloaded from https://modrinth.com/datapack/music-disc-madness/version/2

**Comment by PanchamBro** [comment]
Thanks for letting me know.

As for the resource pack, I need to know if you ended up unzipping the file or left it as it. The data pack will not function unless the proper resource pack is installed.

**Comment by jr0n** [comment]
> As for the resource pack, I need to know if you ended up unzipping the file or left it as it. The data pack will not function unless the proper resource pack is installed.

The resource pack was installed by dropping the zip onto Prism Launcher's "Resource packs" section which copies the zip to:  C:\Users\<user>\AppData\Roaming\PrismLauncher\instances\1.21\.minecraft\resourcepacks\Music Disc Madness Resource Pack.zip

**Comment by PanchamBro** [comment]
Hmm...

Okay, just one more question: did you check your resource pack option to see the pack on the left side of the UI?

**Comment by jr0n** [comment]
> Okay, just one more question: did you check your resource pack option to see the pack on the left side of the UI?

If you're referring to Prism Launcher's enable checkbox, yes, the enable option is checked for 'Music Disc Madness Resource Pack' If you're referring to something else, let me know and I'll take a look. Thanks!

**Comment by PanchamBro** [comment]
When you add a resource pack via Prism Launcher, it will not immediately be activated upon game launch. You need to go into the game's Resource Pack options and select the pack itself to work.

**Comment by jr0n** [comment]
Apologies for the time waste. I thought Prism would auto load Resource Packs from the Prism UI. I needed to manually enable it via the in-game menu:

Screenshot attached for anyone else that might run into this user error in the future.
![image](https://github.com/user-attachments/assets/ce011881-9a1d-4d64-8e1d-054da6cfc4f5)
Thanks for the great mod!

**Comment by PanchamBro** [comment]
No problem man, happy to help out.

Glad you're having fun with my data pack!
